In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [12]:
df = pd.read_csv('../../DataBox/cars.csv')

One Hot encoding Using Pandas

In [13]:
# pd.get_dummies(df,columns=['fuel','owner']) # Here we are creating column for all the categories. 
# -> ## Multicomulticollinearity is Present in This Method ##

# To Avoide Multicomulticollinearity We need to add parameter Drop First
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

# But this method is Totally Random and With every trial we get different Output - Order
# Therefor this method is not Benificial For ML_Models 
# Use SkLearn Class -> It keeps the Order Saved For Future Used

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [14]:
# Encoding Only on Training dataset
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

# Create Object of OneHotEncoder 
# -> *** drop For (K-1) ***
# Sparse_output -> Sparse Array -> if False Numpy Array
# dtype -> Float to Int
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

# Fit And transform Training Dataset
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

# Transform Test Dataset
X_test_new = ohe.transform(X_test[['fuel','owner']])


# add Other Columns from X_train to X_train_new
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [15]:
# Brand Column -> Threshold as 100 -> If less then Others

counts = df['brand'].value_counts()
threshold = 100
repl = counts[counts <= threshold].index
pd.get_dummies(df['brand'].replace(repl, 'others')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
3095,False,False,False,False,False,False,False,False,True,False,False,False,False
1521,False,False,False,False,True,False,False,False,False,False,False,False,False
5499,False,False,False,False,True,False,False,False,False,False,False,False,False
868,False,False,False,False,True,False,False,False,False,False,False,False,False
4217,False,False,False,False,False,False,False,False,False,False,False,False,True